# Generated by Django 4.0.1 on 2022-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Produit', models.CharField(max_length=255)),
                ('Ref', models.CharField(max_length=255)),
                ('Debit', models.FloatField()),
                ('Credit', models.FloatField()),
                ('Solde', models.FloatField()),
                ('Month', models.DateTimeField()),
                ('Year', models.DateTimeField()),
                ('Day', models.DateTimeField()),
            ],
        ),
    ]
