# Generated by Django 4.0.1 on 2022-01-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0002_rename_pdc_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='Year',
            new_name='year',
        ),
    ]
