# Generated by Django 4.0.1 on 2022-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0003_rename_day_budget_day_rename_month_budget_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Fixed_cost', models.FloatField()),
                ('Dsc', models.FloatField()),
                ('invest', models.FloatField()),
                ('Commentaire', models.CharField(max_length=255)),
            ],
        ),
    ]
