# Generated by Django 4.0.1 on 2022-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0004_monthly_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_table',
            name='Month',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
