# Generated by Django 4.0.4 on 2022-04-16 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0006_rename_credit_budget_credit_rename_date_budget_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budget',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthly_table',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthly_table',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
