# Generated by Django 4.0.4 on 2022-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0008_alter_budget_day_alter_budget_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='day',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
