# Generated by Django 4.0.4 on 2022-04-17 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget_app', '0010_remove_budget_date_budget_date_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
